

### Create Product
POST http://localhost:5400/product/createProduct
Content-Type: application/json

{
    "productName": "x-men",
    "productDescription": "Explore breathtaking landscapes and exciting activities.",
    "productPrice": 5000,
    "productCategory": "Electronics",
    "productImage": "https://m.media-amazon.com/images/I/61k7JqSWOUL._SY425_.jpg",
    "supplierContact": "Penguin",
    "Quantity": 20
}

### Get All Products
GET http://localhost:5400/product/

###soft deleted products 
GET http://localhost:5400/product/softDeletedProducts

### restore soft deleted products
put http://localhost:5400/product/restoreProduct
Content-Type: application/json

{
    "productID":"6f2ae277-ba84-4e7a-90e1-5c6f206433ae"
}


### update product

PUT  http://localhost:5400/product/updateProduct
Content-Type: application/json

{   
    "productID":"b549936c-d5b5-43fd-90a3-89bd692cdac0",
    "productName": "Fourteen Falls",
    "productDescription": "adventures",
    "productPrice": 6000,
    "productCategory": "Electronics",
    "productImage": "https://m.media-amazon.com/images/I/61k7JqSWOUL._SY425_.jpg",
    "supplierContact": "Penguins",
    "Quantity": 19
}

###delete product
DELETE  http://localhost:5400/product/deleteProduct
Content-Type: application/json

{   
    "productID":"1f4f8c68-623c-46d1-94ec-10809f673935"
  
}
